behaviors:
  PlatformerAgent:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 0.0003
      batch_size: 128
      buffer_size: 12000
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 10_000_000
    time_horizon: 64
    summary_freq: 20000
    num_layers: 3
    hidden_units: 256
    network_settings:
      normalize: true